//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodget.RDLC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceRDLC {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceRDLC() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bodget.RDLC.ResourceRDLC", typeof(ResourceRDLC).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par mois et catégories.
        /// </summary>
        internal static string MoisCategoriesTitle {
            get {
                return ResourceManager.GetString("MoisCategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez oublier de passer le ReportDataSource &apos;{0}&apos; qui est demandé dans ce raport. Ajouter le à : Dictionary&lt;string, object&gt; ReportDataSources.
        /// </summary>
        internal static string ReportMng_Invalid_DataSrc {
            get {
                return ResourceManager.GetString("ReportMng_Invalid_DataSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez oublier de passer le ReportParameter &apos;{0}&apos; qui est demandé dans ce raport. Ajouter le à : Dictionary&lt;string, object&gt; ReportDataSources.
        /// </summary>
        internal static string ReportMng_Invalid_DataSrc4Parameter {
            get {
                return ResourceManager.GetString("ReportMng_Invalid_DataSrc4Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIXME.
        /// </summary>
        internal static string RessourceNonTrouvee {
            get {
                return ResourceManager.GetString("RessourceNonTrouvee", resourceCulture);
            }
        }
    }
}
