//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libod {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Libod.ResourceText", typeof(ResourceText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} du fichier à {1}.
        /// </summary>
        public static string _duFichierA_ {
            get {
                return ResourceManager.GetString("_duFichierA_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à.
        /// </summary>
        public static string aAccentue {
            get {
                return ResourceManager.GetString("aAccentue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alors.
        /// </summary>
        public static string alors {
            get {
                return ResourceManager.GetString("alors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exite déjà.
        /// </summary>
        public static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Après.
        /// </summary>
        public static string Apres {
            get {
                return ResourceManager.GetString("Apres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avril.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Août.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banque inconu (création automatique).
        /// </summary>
        public static string AutoNomBanque {
            get {
                return ResourceManager.GetString("AutoNomBanque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiare inconu (création automatique).
        /// </summary>
        public static string AutoNomBeneficiare {
            get {
                return ResourceManager.GetString("AutoNomBeneficiare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte inconu (création automatique).
        /// </summary>
        public static string AutoNomCompte {
            get {
                return ResourceManager.GetString("AutoNomCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banquaire.
        /// </summary>
        public static string banquaire {
            get {
                return ResourceManager.GetString("banquaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banque.
        /// </summary>
        public static string Banque {
            get {
                return ResourceManager.GetString("Banque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banques.
        /// </summary>
        public static string Banques {
            get {
                return ResourceManager.GetString("Banques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiare.
        /// </summary>
        public static string Beneficiare {
            get {
                return ResourceManager.GetString("Beneficiare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BlankValue {
            get {
                return ResourceManager.GetString("BlankValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ce.
        /// </summary>
        public static string ce {
            get {
                return ResourceManager.GetString("ce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cet.
        /// </summary>
        public static string cet {
            get {
                return ResourceManager.GetString("cet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cette.
        /// </summary>
        public static string cette {
            get {
                return ResourceManager.GetString("cette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chèque.
        /// </summary>
        public static string cheque {
            get {
                return ResourceManager.GetString("cheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classement.
        /// </summary>
        public static string Classement {
            get {
                return ResourceManager.GetString("Classement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nettoyer.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string colon {
            get {
                return ResourceManager.GetString("colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colonne.
        /// </summary>
        public static string column {
            get {
                return ResourceManager.GetString("column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string coma {
            get {
                return ResourceManager.GetString("coma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte.
        /// </summary>
        public static string Compte {
            get {
                return ResourceManager.GetString("Compte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contient le texte suivante.
        /// </summary>
        public static string ContainThisText {
            get {
                return ResourceManager.GetString("ContainThisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contient .
        /// </summary>
        public static string contient {
            get {
                return ResourceManager.GetString("contient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to couleur.
        /// </summary>
        public static string couleur {
            get {
                return ResourceManager.GetString("couleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        public static string CrochetFermant {
            get {
                return ResourceManager.GetString("CrochetFermant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        public static string CrochetOuvrant {
            get {
                return ResourceManager.GetString("CrochetOuvrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d&apos;.
        /// </summary>
        public static string d_ {
            get {
                return ResourceManager.GetString("d_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dans.
        /// </summary>
        public static string dans {
            get {
                return ResourceManager.GetString("dans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string dash {
            get {
                return ResourceManager.GetString("dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jour.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décembre.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to depuis.
        /// </summary>
        public static string depuis {
            get {
                return ResourceManager.GetString("depuis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to des.
        /// </summary>
        public static string des {
            get {
                return ResourceManager.GetString("des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devez.
        /// </summary>
        public static string devez {
            get {
                return ResourceManager.GetString("devez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affichage.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donne.
        /// </summary>
        public static string donne {
            get {
                return ResourceManager.GetString("donne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donné.
        /// </summary>
        public static string donne_ {
            get {
                return ResourceManager.GetString("donne_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string dot {
            get {
                return ResourceManager.GetString("dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.
        /// </summary>
        public static string e {
            get {
                return ResourceManager.GetString("e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emis.
        /// </summary>
        public static string emis {
            get {
                return ResourceManager.GetString("emis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encaissé.
        /// </summary>
        public static string encaisse_ {
            get {
                return ResourceManager.GetString("encaisse_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        public static string exclamation_mark {
            get {
                return ResourceManager.GetString("exclamation_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exporter.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Février.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fichier.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des règles pour la catégorisation automatique.
        /// </summary>
        public static string FrmCategorizationAutoTitle {
            get {
                return ResourceManager.GetString("FrmCategorizationAutoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des colonnes.
        /// </summary>
        public static string FrmColumnTitle {
            get {
                return ResourceManager.GetString("FrmColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche (pas de fini de développer, vaut mieux ne pas l&apos;utiliser).
        /// </summary>
        public static string FrmFindTitle {
            get {
                return ResourceManager.GetString("FrmFindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodget.
        /// </summary>
        public static string FrmMainTitle {
            get {
                return ResourceManager.GetString("FrmMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sans titre.
        /// </summary>
        public static string FrmReportViewerTitle {
            get {
                return ResourceManager.GetString("FrmReportViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des {0}.
        /// </summary>
        public static string GestionDes {
            get {
                return ResourceManager.GetString("GestionDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-tête.
        /// </summary>
        public static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si dans {0} {1}.
        /// </summary>
        public static string IfInModeleTheProperty {
            get {
                return ResourceManager.GetString("IfInModeleTheProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to importer.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initiales.
        /// </summary>
        public static string initiales {
            get {
                return ResourceManager.GetString("initiales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j.
        /// </summary>
        public static string j {
            get {
                return ResourceManager.GetString("j", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janvier.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juillet.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juin.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la.
        /// </summary>
        public static string la {
            get {
                return ResourceManager.GetString("la", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to largeur.
        /// </summary>
        public static string largeur {
            get {
                return ResourceManager.GetString("largeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le.
        /// </summary>
        public static string le {
            get {
                return ResourceManager.GetString("le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des {0} à {1}.
        /// </summary>
        public static string ListDes_a_ {
            get {
                return ResourceManager.GetString("ListDes_a_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des {0} existantes.
        /// </summary>
        public static string ListDes_Existantes {
            get {
                return ResourceManager.GetString("ListDes_Existantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des {0} existants.
        /// </summary>
        public static string ListDes_Existants {
            get {
                return ResourceManager.GetString("ListDes_Existants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liste.
        /// </summary>
        public static string liste {
            get {
                return ResourceManager.GetString("liste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gérer.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mars.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mettre.
        /// </summary>
        public static string mettre {
            get {
                return ResourceManager.GetString("mettre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mois.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doit être supérieur à 0.
        /// </summary>
        public static string MoreThanZero {
            get {
                return ResourceManager.GetString("MoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nom.
        /// </summary>
        public static string nom {
            get {
                return ResourceManager.GetString("nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre.
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novembre.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octobre.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opération.
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        public static string parentheseFermante {
            get {
                return ResourceManager.GetString("parentheseFermante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        public static string parentheseOuvrante {
            get {
                return ResourceManager.GetString("parentheseOuvrante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string pound {
            get {
                return ResourceManager.GetString("pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimer.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to propriété.
        /// </summary>
        public static string propriete {
            get {
                return ResourceManager.GetString("propriete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string question_mark {
            get {
                return ResourceManager.GetString("question_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rapprochement.
        /// </summary>
        public static string rapprochement {
            get {
                return ResourceManager.GetString("rapprochement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recherchée.
        /// </summary>
        public static string recherchee {
            get {
                return ResourceManager.GetString("recherchee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recherche.
        /// </summary>
        public static string research {
            get {
                return ResourceManager.GetString("research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to règle.
        /// </summary>
        public static string rule {
            get {
                return ResourceManager.GetString("rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Règles.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saisir.
        /// </summary>
        public static string saisir {
            get {
                return ResourceManager.GetString("saisir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        public static string semi_colon {
            get {
                return ResourceManager.GetString("semi_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septembre.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to si.
        /// </summary>
        public static string si {
            get {
                return ResourceManager.GetString("si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        public static string slash {
            get {
                return ResourceManager.GetString("slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soit.
        /// </summary>
        public static string soit {
            get {
                return ResourceManager.GetString("soit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string star {
            get {
                return ResourceManager.GetString("star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supprimer.
        /// </summary>
        public static string supprimer {
            get {
                return ResourceManager.GetString("supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to texte.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alors, ajouter automatiquement l&apos;opération dans la catégorie :.
        /// </summary>
        public static string ThenAddOperationInCategory {
            get {
                return ResourceManager.GetString("ThenAddOperationInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string tiret {
            get {
                return ResourceManager.GetString("tiret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to un.
        /// </summary>
        public static string un {
            get {
                return ResourceManager.GetString("un", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to une.
        /// </summary>
        public static string une {
            get {
                return ResourceManager.GetString("une", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valeur.
        /// </summary>
        public static string valeur {
            get {
                return ResourceManager.GetString("valeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visible.
        /// </summary>
        public static string visible {
            get {
                return ResourceManager.GetString("visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vos.
        /// </summary>
        public static string vos {
            get {
                return ResourceManager.GetString("vos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous.
        /// </summary>
        public static string vous {
            get {
                return ResourceManager.GetString("vous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to largeur.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        public static string x {
            get {
                return ResourceManager.GetString("x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to année.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous devez saisir {0}.
        /// </summary>
        public static string YouMustEnter {
            get {
                return ResourceManager.GetString("YouMustEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous devez saisir {0} contenu dans {1}.
        /// </summary>
        public static string YouMustEnterContainIn {
            get {
                return ResourceManager.GetString("YouMustEnterContainIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vous devez choisir {0} dans la liste.
        /// </summary>
        public static string YouMustToChooseInList {
            get {
                return ResourceManager.GetString("YouMustToChooseInList", resourceCulture);
            }
        }
    }
}
